### ISSUE TITLE
our projects page - images need to slide to the other direction - rtl

### ISSUE THREAD

**Issue by danasegal1** [uidb-dev/ui-db---frontEnd#63]
on the second level of `our projects` page, rtl version only - the images automatically slides from the first to the last image. it should be from the first to the second.

**Comment by touhidbd** [comment]
Solved

**Comment by orchoban** [comment]
The problem is that on RTL it start on image #1, and aromatic slide to to last image after (need to slide left)

**Comment by touhidbd** [comment]
@orchoban I try to find out the issues. I make numeric serial and it's working well on `rtl` version. Could you please check the image query?

https://share.vidyard.com/watch/eikbQ9qjyZq6Ey7Bk1y3tM?

**Comment by orchoban** [comment]
Thank you for check it out.
I think it appeared after reload with Hebrew, But let me check it again.
