### ISSUE TITLE
change header while scrolling

### ISSUE THREAD

**Issue by danasegal1** [uidb-dev/ui-db---frontEnd#69]
when scrolling down change the header to closed hamburger

from this
![image](https://user-images.githubusercontent.com/95017644/147679886-66b09e73-fdc7-4eb1-887b-17b283ffc452.png)
to 
![image](https://user-images.githubusercontent.com/95017644/147679999-4c013e15-4bf7-46db-a4e0-18d0bd0561bc.png)

**Comment by touhidbd** [comment]
Update
