### ISSUE TITLE
navigation-controller and react cordova on Hebrew.

### ISSUE THREAD

**Issue by orchuban** [uidb-dev/ui-db---frontEnd#70]
Hi, I published the open-source pages.

In this part I need class like `ltr_text` for English text.
I need the option to remove this class and back to `rtl`
Please see example:
![image](https://user-images.githubusercontent.com/33927385/147828316-9279af04-a451-4618-9dac-e197ef44fec1.png)

online:
https://ui-db.com/he/open-source/navigation-controller
https://ui-db.com/he/open-source/react.cordova

**Comment by touhidbd** [comment]
Update. Please check

**Comment by orchoban** [comment]
![image](https://user-images.githubusercontent.com/33927385/147857269-fbbca5f0-8c0a-4d4a-a886-8ebf35b38cda.png)

**Comment by orchuban** [comment]
@touhidbd 
Please review the page
> ![image](https://user-images.githubusercontent.com/33927385/147857269-fbbca5f0-8c0a-4d4a-a886-8ebf35b38cda.png)

**Comment by touhidbd** [comment]
Update.
