### ISSUE TITLE
reduce the gap - on home page - web version

### ISSUE THREAD

**Issue by danasegal1** [uidb-dev/ui-db---frontEnd#71]
There is too much gap that needs to reduced on home page - LTR and RTL
This is how it looks now on the website
<img width="862" alt="Screen Shot 2022-01-03 at 19 48 16" src="https://user-images.githubusercontent.com/95017644/147963115-0ac438bf-83c0-4372-a994-6987aba31ca0.png">

This is how it should look like
<img width="634" alt="Screen Shot 2022-01-03 at 19 49 56" src="https://user-images.githubusercontent.com/95017644/147963150-7820f9ff-1458-40cd-bee4-24b885ad8a36.png">

**Comment by touhidbd** [comment]
Update

**Comment by danasegal1** [comment]
It isn't right on page dimensions of 1920x1080

<img width="1065" alt="Screen Shot 2022-01-09 at 9 35 22" src="https://user-images.githubusercontent.com/95017644/148673513-2c1e2488-093c-4872-b27c-f5ec429f66f5.png">
