### ISSUE TITLE
Change the "satisfied customers" section headline - home page 

### ISSUE THREAD

**Issue by danasegal1** [uidb-dev/ui-db---frontEnd#73]
Change the headline from "satisfied customers" to "Clients" - English only
Please check it on translation.json only

<img width="663" alt="Screen Shot 2022-01-03 at 20 10 32" src="https://user-images.githubusercontent.com/95017644/147965187-9b86e4bd-fabb-4360-8027-af2b7dd1e898.png">

**Comment by orchuban** [comment]
Done
