### ISSUE TITLE
Show one image at a time on 'our projects' section - home page, mobile version

### ISSUE THREAD

**Issue by danasegal1** [uidb-dev/ui-db---frontEnd#74]
On 'our projects' section in home page, show one large image at a time instead of two small images - on mobile version in both LTR and RTL 
<img width="298" alt="Screen Shot 2022-01-03 at 20 29 09" src="https://user-images.githubusercontent.com/95017644/147966154-163a9227-8be7-4720-85df-f916b8cb5353.png">

**Comment by touhidbd** [comment]
Update
