### ISSUE TITLE
Margin should be wider on 'home page' 'about us' section - mobile version

### ISSUE THREAD

**Issue by danasegal1** [uidb-dev/ui-db---frontEnd#75]
On 'home page' at the  'about us' section, make the margin larger - on mobile version both LTR and RTL

This is how it looks now
<img width="299" alt="Screen Shot 2022-01-03 at 20 32 32" src="https://user-images.githubusercontent.com/95017644/147966862-5985f77b-0092-44f3-9d1d-aa221c456831.png">

This is how it should be
<img width="288" alt="Screen Shot 2022-01-03 at 20 34 30" src="https://user-images.githubusercontent.com/95017644/147966879-0b965b56-003b-410e-9412-d026698f7640.png">

**Comment by touhidbd** [comment]
Update
