### ISSUE TITLE
Fixing for "clients" section on home page - mobile version

### ISSUE THREAD

**Issue by danasegal1** [uidb-dev/ui-db---frontEnd#76]
<img width="298" alt="Screen Shot 2022-01-03 at 20 39 50" src="https://user-images.githubusercontent.com/95017644/147967542-eeae3c04-dbcf-40ab-a724-9742c7f03e9c.png">

please make the following changes on both RTL and LTR versions 
for square 1:
 - lower the headline down
 for square 2:
- Limit the size of the clients's logos 
- Show only two logos at a time instead of three
- Add maximum height

**Comment by touhidbd** [comment]
Update
