### ISSUE TITLE
Fixing on footer - mobile version

### ISSUE THREAD

**Issue by danasegal1** [uidb-dev/ui-db---frontEnd#77]
<img width="302" alt="Screen Shot 2022-01-03 at 20 55 54" src="https://user-images.githubusercontent.com/95017644/147968864-8e0b9c90-e52c-4636-a95a-c534beaa9002.png">

please fix the following for the footer in the mobile version - both LTR and RTL
Squares 1 - The grid is not good - margin too small, it should be bigger
Square 2 - The logo is too big - need to be smaller

This is how it should be
<img width="290" alt="Screen Shot 2022-01-03 at 21 02 05" src="https://user-images.githubusercontent.com/95017644/147969245-6fe06294-cf0c-49ce-9426-cb0f420f01e0.png">

**Comment by touhidbd** [comment]
Update
