### ISSUE TITLE
'our-projects' page - points from meeting

### ISSUE THREAD

**Issue by danasegal1** [uidb-dev/ui-db---frontEnd#80]
Points from the meeting with Liad about Our-Projects page:

- [x]  Need to Increase the size of the images - pay attention to the grid

- [x]  New design for preview: 70% opacity with middle headline and description, little icons (of IOS, Android Etc..) on the left side (LTR & RTL) #85

**Comment by orchuban** [comment]
Great.
I gave the Liad to design it on XD

**Comment by touhidbd** [comment]
Update. Please check
