### ISSUE TITLE
project page of "Below the crime" on mobile - try me section is cut

### ISSUE THREAD

**Issue by danasegal1** [uidb-dev/ui-db---frontEnd#82]
On the project page of "Below the crime" on mobile version the "try me" section is getting cut.
Please talk to Or and he will guide you how to fix it via wordpress
![image](https://user-images.githubusercontent.com/95017644/148252917-9f2cf160-e941-42bd-bcd7-4dc1461eed8e.png)

Here is the link to the page
https://ui-db.com/en/projects/156

**Comment by orchuban** [comment]
@touhidbd.
I sended you email with information about how to connect to the admin panel.
You can find this project on `projects` category and see "BelowTheCrime" project.
Let me know if have any problem.

**Comment by touhidbd** [comment]
Update

**Comment by orchuban** [comment]
![image](https://user-images.githubusercontent.com/33927385/148673130-f6cbd95f-fb99-4fc5-9410-aa9708443bdf.png)
![image](https://user-images.githubusercontent.com/33927385/148673141-4a751abe-1a65-4ca9-b753-88f239d6fe8b.png)

@touhidbd please try to edit it from admin panel
![image](https://user-images.githubusercontent.com/33927385/148673194-55545f0c-d603-44be-81d6-18bd850d2a1a.png)
Please contact me on project for mor details

**Comment by orchuban** [comment]
@danasegal1 
Why you close it?
![image](https://user-images.githubusercontent.com/33927385/148684212-4fb2d062-763d-46c7-9284-10a91875c6bc.png)

**Comment by touhidbd** [comment]
@orchuban Update, I hope now it's solved. I fix it with CSS because in a responsive the embed width and height code with not working properly. Please check. Sometimes it seemed no scrollbar maybe that's why he closed the issues.
