### ISSUE TITLE
new design for projects

### ISSUE THREAD

**Issue by orchuban** [uidb-dev/ui-db---frontEnd#85]
Follow XD.

use title: ``` project.acf[`${props.i18n.language}_title`] ```
use description: ``` project.acf[`${props.i18n.language}_description`] ```
_limit maximum description text. If longer, cut it and put "..."_

mobile:
 ![image](https://user-images.githubusercontent.com/33927385/148794137-34a7b8fe-8f63-4ed6-84c4-780fb3d2a9fe.png)
Desktop (on mouse over) 
![image](https://user-images.githubusercontent.com/33927385/148794293-dfb419d5-0875-4fd4-8c0e-9d778f544916.png)

**Comment by touhidbd** [comment]
@orchuban Update. Please help me to make this part diynamic. Thank you. 
![image](https://user-images.githubusercontent.com/8915879/149064558-80d84223-f25d-44df-bb0d-710c6a6706f4.png)

**Comment by orchuban** [comment]
> @orchuban Update. Please help me to make this part diynamic. Thank you. ![image](https://user-images.githubusercontent.com/8915879/149064558-80d84223-f25d-44df-bb0d-710c6a6706f4.png)

Done

**Comment by orchuban** [comment]
@touhidbd  I moved the `Link` to be on all hove the component.
![image](https://user-images.githubusercontent.com/33927385/149089840-82c363cb-9b6f-4fbe-9f1c-b5f9c7584bfb.png)

Now mobile style damage 
![image](https://user-images.githubusercontent.com/33927385/149090076-0b1289ef-0687-45c8-9710-ffa56f106f14.png)

**Comment by touhidbd** [comment]
Update. Please check

**Comment by orchuban** [comment]
![image](https://user-images.githubusercontent.com/33927385/149724437-343321a6-918e-4441-bb20-fc63bec9b48c.png)

**Comment by orchuban** [comment]
> ![image](https://user-images.githubusercontent.com/33927385/149724437-343321a6-918e-4441-bb20-fc63bec9b48c.png)

@touhidbd please check icons on project page. When we create this issue them move

**Comment by touhidbd** [comment]
Fixed. Please check
